# Section A – Conceptual Understanding
### A1. Why are NumPy arrays generally preferred over plain Python lists for numerical computation in AI/ML workloads? Mention at least two concrete reasons. 

## Answer:
NumPy arrays are preferred over Python lists in AI/ML because:

-> Faster: NumPy arrays can perform calculations on many values at once, so they are faster than Python lists for numerical operations.
-> Memory efficient: NumPy stores data in a compact way, so it uses less memory than normal Python lists.

### A2. Explain vectorization. Why does replacing an explicit Python loop with a vectorized NumPy operation matter with large datasets?

# Answer:
-> Vectorization means performing an operation on the whole NumPy array at once instead of using a for loop for each value.
-> It is useful for large datasets because NumPy can perform calculations faster and the code is shorter and easier to write.

### A3. For compatible 2D arrays A and B, explain A * B vs A @ B. Describe one neural-network situation for each.

# Answer:
--> A * B → Performs element-by-element multiplication. Each value in A is multiplied with the value at the same position in B.
Neural-network use: Useful when applying a mask or scaling values in a layer.
--> A @ B → Performs matrix multiplication, where rows of A are multiplied with columns of B.
Neural-network use: Used when calculating a layer’s output from input data and weights.


### A4. What is broadcasting in NumPy? State the general rule used to decide whether arrays of different shapes can be combined element-wise.

# Answer:
-> Broadcasting is a NumPy feature where a smaller array or value is automatically used with a larger array during element-wise operations, without manually changing its size.
-> General rule: Compare the shapes from the rightmost dimension. The dimensions are compatible if they are equal or one of them is 1. Otherwise, broadcasting is not possible.

### A5. Explain flatten() vs ravel(). In a memory-constrained application processing large images, which would you prefer and why?

# Answer:
flatten() and ravel() both convert a multi-dimensional array into a 1D array. flatten() creates a new copy, while ravel() usually gives a view of the original array. 
For large images when memory is limited, I would prefer ravel() because it usually uses less memory.


### A6. For a 2D array, explain axis=0 and axis=1 in an aggregation function such as np.sum() or np.mean(). Illustrate with a small example.

# Answer:
axis=0 calculates the aggregation column-wise, while axis=1 calculates it row-wise.


In [2]:
import numpy as np
array=np.array([[10,20,30],
               [10,20,30]])
print("column wise sum:", np.sum(array, axis=0))
print("column wise mean:", np.mean(array, axis=0))
print("row wise sum:", np.sum(array, axis=1))
print("row wise mean:", np.mean(array, axis=1))

column wise sum: [20 40 60]
column wise mean: [10. 20. 30.]
row wise sum: [60 60]
row wise mean: [20. 20.]


### A7. Why is it important to normalize or standardize numerical features before training most ML models? Explain normalization vs standardization.

# Answer:
Normalization and standardization are used to bring numerical features to a similar scale, so that features with large values do not dominate the model. Normalization usually converts values to a range of 0 to 1, while standardization converts values using the mean and standard deviation, giving a mean of 0 and standard deviation of 1.


### A8. Why do functions such as np.nanmean() exist? What happens if np.mean() is used directly on data containing NaN? 

# Answer:
-> np.nanmean() is used to calculate the mean while ignoring NaN (missing) values.
-> If we use np.mean() on data containing NaN, the result will usually be NaN, because the missing value affects the calculation.


### A9. In the ML convention X.shape = (samples, features), explain how this extends to a batch of RGB images. Write the exact shape for 64 RGB images of size 128 × 128.

# Answer:
For a batch of RGB images, the shape is:
(samples, height, width, channels)

64 → number of images (samples)
128 → image height
128 → image width
3 → RGB channels (Red, Green, Blue)

So, for 64 RGB images of size 128 × 128, the exact shape is:
(64, 128, 128, 3)
Simple meaning: 64 images, each with 128 rows × 128 columns, and 3 color channels.

### A10. Why is reproducibility important during model development and experimentation? Refer to fixing a random seed with np.random.default_rng(seed). 

# Answer:
Reproducibility means getting the same results when we run the same experiment again. It helps us check and compare our results easily.
We can fix a random seed using np.random.default_rng(seed). This makes NumPy generate the same random values each time.


In [4]:
import numpy as np
array=np.random.default_rng(42)
print(array.random(3))

[0.77395605 0.43887844 0.85859792]


# Section B – Predict the Output

### B1. Predict the exact output and/or resulting shape. Justify in one sentence. [2 marks]
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print((a + b).shape)

# predicted output:
(3, 3)

#### Explanation: a has 3 elements and b has 3 rows with 1 column. When we add them, NumPy uses broadcasting and produces a 3 × 3 array. Therefore, the shape of a + b is (3, 3).  



### B2. Predict the output and/or shape. [2 marks]
x = np.arange(1, 7).reshape(2, 3)
print(x[:, 1])

# predicted output:
[2 5]
#### Explanation: : selects all rows and 1 selects the second column, so the result is [2, 5].

### B3. Predict the output and/or shape. [2 marks]
arr = np.array([5, 10, 15, 20, 25])
print(arr[arr % 10 == 0])

# predicted output:
[10 20]
Explanation: The condition arr % 10 == 0 selects the numbers that are exactly divisible by 10, so the output is [10 20].

### B4. Predict the output and/or shape. [2 marks]
m = np.array([[1, 2], [3, 4]])
print(m.T @ m)

# predicted output:
[[10 14]
 [14 20]]
#### Explanation: m.T transposes the matrix, and @ performs matrix multiplication. The resulting shape is (2, 2).

### B5. Predict the output and/or shape. [2 marks]
data = np.array([1, 2, np.nan, 4])
print(np.mean(data), np.nanmean(data))

# predicted output:
nan 2.3333333333333335
#### Explanation: np.mean() returns nan when a NaN value is present, while np.nanmean() ignores NaN values and returns the mean of the remaining values, which is 2.33.

### B6. Predict the output and/or shape. [2 marks]
x = np.array([10, 20, 30])
y = np.where(x > 15, 1, 0)
print(y)

# predicted output:
[0 1 1]
Explanation: np.where() checks each value against 15 and returns 1 if it is greater than 15, otherwise 0.

### B7. Predict the output and/or shape. [2 marks]
a = np.zeros((3, 4))
print(a.ndim, a.size)

# predicted output:
2 12
#### Explanation: a.ndim → number of dimensions = 2 because it has 3 rows and 4 columns.
             a.size → total number of elements = 3 × 4 = 12.

### B8. Predict the output and/or shape. [2 marks]
arr = np.arange(1, 13).reshape(3, 4)
print(arr[::-1, ::-1])

# predicted output:
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
#### Explanation: 
[::-1] → reverses the rows
[::-1] → reverses the columns
Both rows and columns are reversed, so the shape remains (3, 4).

# Section C – Coding / Implementaion

In [1]:
#C1. Given a 1D NumPy array of exam scores, use np.where() to produce labels 'P' (score >= 40) or 'F' (score < 40). 
import numpy as np
scores=np.array([70,35,78,28,90])
print(np.where(scores>=40,"P", "F"))


['P' 'F' 'P' 'F' 'P']


In [3]:
#C2. Write a function standardize(x) that takes a 1D NumPy array and returns its z-score standardized version using only NumPy. 
x=np.array([70,50,60,78,69])
mean=np.mean(x)
z_scores=(x-mean)/np.std(x)
print(z_scores.round(2))

[ 0.48 -1.61 -0.56  1.31  0.38]


In [4]:
#C3. Given two 2D NumPy arrays representing separate batches with the same number of features, combine them using an appropriate NumPy stacking function and print the resulting shape.
array1=np.array([[1,2,3],
                 [4,5,6]])
array2=np.array([[6,5,4],
                 [3,2,1]])
print(np.concatenate((array1,array2)).shape)



(4, 3)


In [6]:
#C4. Given X with shape (100, 5), compute column-wise mean and standard deviation and standardize the matrix in one vectorized expression. 
x=np.arange(1, 501).reshape(100,5)
avg=np.mean(x, axis=0)
print(((x-avg)/np.std(x, axis=0)).round(2))


[[-1.71 -1.71 -1.71 -1.71 -1.71]
 [-1.68 -1.68 -1.68 -1.68 -1.68]
 [-1.65 -1.65 -1.65 -1.65 -1.65]
 [-1.61 -1.61 -1.61 -1.61 -1.61]
 [-1.58 -1.58 -1.58 -1.58 -1.58]
 [-1.54 -1.54 -1.54 -1.54 -1.54]
 [-1.51 -1.51 -1.51 -1.51 -1.51]
 [-1.47 -1.47 -1.47 -1.47 -1.47]
 [-1.44 -1.44 -1.44 -1.44 -1.44]
 [-1.4  -1.4  -1.4  -1.4  -1.4 ]
 [-1.37 -1.37 -1.37 -1.37 -1.37]
 [-1.33 -1.33 -1.33 -1.33 -1.33]
 [-1.3  -1.3  -1.3  -1.3  -1.3 ]
 [-1.26 -1.26 -1.26 -1.26 -1.26]
 [-1.23 -1.23 -1.23 -1.23 -1.23]
 [-1.2  -1.2  -1.2  -1.2  -1.2 ]
 [-1.16 -1.16 -1.16 -1.16 -1.16]
 [-1.13 -1.13 -1.13 -1.13 -1.13]
 [-1.09 -1.09 -1.09 -1.09 -1.09]
 [-1.06 -1.06 -1.06 -1.06 -1.06]
 [-1.02 -1.02 -1.02 -1.02 -1.02]
 [-0.99 -0.99 -0.99 -0.99 -0.99]
 [-0.95 -0.95 -0.95 -0.95 -0.95]
 [-0.92 -0.92 -0.92 -0.92 -0.92]
 [-0.88 -0.88 -0.88 -0.88 -0.88]
 [-0.85 -0.85 -0.85 -0.85 -0.85]
 [-0.81 -0.81 -0.81 -0.81 -0.81]
 [-0.78 -0.78 -0.78 -0.78 -0.78]
 [-0.74 -0.74 -0.74 -0.74 -0.74]
 [-0.71 -0.71 -0.71 -0.71 -0.71]
 [-0.68 -0

In [2]:
#C5. Implement y_pred = X @ w + b for a feature matrix X, weight vector w and bias b. Then compute MSE using y_true.
import numpy as np
X=np.array([[1,2,3],
           [4,5,6]])
w=np.array([8,7,9])
b=1
y_true=np.array([10,20])
y_pred=X @ w + b
mse= np.mean((y_true-y_pred)**2)
print(mse)


6002.0


In [ ]:
#C6. Using np.random.default_rng() with a fixed seed, generate 10 samples and 3 features from a normal distribution. Print the shape and confirm identical results with the same seed. 
rng1=np.random.default_rng(42)
arr1=rng1.normal(size=(10, 3))
print("Shape:", arr1.shape)
rng2=np.random.default_rng(42)
arr2=rng2.normal(size=(10, 3))
print("Identical results:", np.array_equal(arr1, arr2))


Shape: (10, 3)
Identical results: True


In [5]:
#C7. Given a grayscale image as a 2D NumPy array with pixel values in [0, 255], normalize the values to [0, 1] using min-max normalization.
image = np.array([
    [0, 54, 12],
    [12, 255, 42],
    [101, 202, 90]
])
min=image.min()
max=image.max()
normalized_image=(image-min) / (max-min)
print("Original image:")
print(image)
print("\nNormalized image:")
print(normalized_image.round(2))

Original image:
[[  0  54  12]
 [ 12 255  42]
 [101 202  90]]

Normalized image:
[[0.   0.21 0.05]
 [0.05 1.   0.16]
 [0.4  0.79 0.35]]


In [6]:
#C8. Given 4 RGB images of shape (28, 28, 3), stored as shape (4, 28, 28, 3), compute the average pixel value of each image across height, width and channels. State the axis argument and why. 
image=np.arange(1,9409).reshape(4, 28, 28, 3)
print(np.mean(image, axis=(1,2,3)))


[1176.5 3528.5 5880.5 8232.5]


# Section D – Applied / Scenario-Based Problems

In [ ]:
#You are given a raw 1D or 2D NumPy array containing NaN values.
#Describe, step by step, the NumPy operations you would apply to:
#(a) detect missing values,
#(b) handle them appropriately and justify your strategy, and
#(c) normalize or standardize the clean data before it is fed to a model.

#Implement the full pipeline in code on a sample array of your own choosing, including at least one NaN.

arr=np.array([[10,20,np.nan],
             [np.nan,3,4]])
print(np.isnan(arr))
median=np.nanmedian(arr)
replace=np.where(np.isnan(arr),median,arr)
print(replace)
min=replace.min()
max=replace.max()
print((replace-min)/(max-min))






[[False False  True]
 [ True False False]]
[[10. 20.  7.]
 [ 7.  3.  4.]]
[[0.41176471 1.         0.23529412]
 [0.23529412 0.         0.05882353]]


# Explanation: 
 First, I detect missing values using NumPy's isnan() operation. Then I handle the missing values by replacing them with the median of the available values. I choose the median because it is less affected by extreme values. After obtaining clean data, I apply Min-Max normalization to scale the values to the range 0 to 1 before feeding them into the machine-learning model.


## 1.Explain, with correct NumPy shapes, how a single RGB image differs from a batch of RGB images

A single RGB image of size 64 × 64 has the shape (64, 64, 3).
64 → Height
64 → Width
3 → RGB channels

A batch of 16 RGB images has the shape (16, 64, 64, 3).
16 → Number of images
64 → Height
64 → Width
3 → RGB channels

So, a batch has one extra dimension for the number of images.

In [9]:
#2. Write code to create a dummy batch of 16 images of size 64 × 64 using random pixel values.
dummy=np.random.default_rng(42)
images=dummy.integers(0, 255, size=(16,64,64,3))
print(images.shape)


(16, 64, 64, 3)


In [10]:
#3. Compute the average image of the batch, meaning the element-wise mean across all 16 images.
image=np.arange(196608).reshape(16, 64, 64, 3)
print(np.mean(image, axis=0))



[[[ 92160.  92161.  92162.]
  [ 92163.  92164.  92165.]
  [ 92166.  92167.  92168.]
  ...
  [ 92343.  92344.  92345.]
  [ 92346.  92347.  92348.]
  [ 92349.  92350.  92351.]]

 [[ 92352.  92353.  92354.]
  [ 92355.  92356.  92357.]
  [ 92358.  92359.  92360.]
  ...
  [ 92535.  92536.  92537.]
  [ 92538.  92539.  92540.]
  [ 92541.  92542.  92543.]]

 [[ 92544.  92545.  92546.]
  [ 92547.  92548.  92549.]
  [ 92550.  92551.  92552.]
  ...
  [ 92727.  92728.  92729.]
  [ 92730.  92731.  92732.]
  [ 92733.  92734.  92735.]]

 ...

 [[103872. 103873. 103874.]
  [103875. 103876. 103877.]
  [103878. 103879. 103880.]
  ...
  [104055. 104056. 104057.]
  [104058. 104059. 104060.]
  [104061. 104062. 104063.]]

 [[104064. 104065. 104066.]
  [104067. 104068. 104069.]
  [104070. 104071. 104072.]
  ...
  [104247. 104248. 104249.]
  [104250. 104251. 104252.]
  [104253. 104254. 104255.]]

 [[104256. 104257. 104258.]
  [104259. 104260. 104261.]
  [104262. 104263. 104264.]
  ...
  [104439. 104440. 10444

## 4. state the shape of your result and explain why.

The result shape is (64, 64, 3).

The original batch has shape (16, 64, 64, 3), where 16 represents the number of images. We use axis=0 to calculate the element-wise mean across all 16 images. Therefore, the first dimension is removed, while the height, width, and RGB channels remain.

Batch shape: (16, 64, 64, 3)
Average image shape: (64, 64, 3)

## D3. Debug the Model Code [8 marks]
The following code contains more than one bug:

X = np.array([[1, 2],
              [2, 3],
              [3, 4]])  # shape (3, 2)
w = np.array([0.5, 1.0, 0.2])  # intended weight vector
b = 2.0
y_pred = X @ w + b
y_true = np.array([10, 20, 30])
mse = np.mean(y_true - y_pred ** 2)
Identify every bug. Explain, in terms of shapes and operator precedence, why each is a problem, and rewrite the corrected code.

Answer:

There are two bugs in the given code:

Bug 1: Incorrect shape of w

X has shape (3, 2), which means there are 3 samples and 2 features. Therefore, the weight vector must contain 2 weights. But the given w has 3 values, so X @ w is not valid.

The corrected weight vector is:

w = np.array([0.5, 1.0])

Now X has shape (3, 2) and w has shape (2,), so X @ w produces 3 predicted values.

Bug 2: Incorrect MSE expression due to operator precedence

The given expression:

mse = np.mean(y_true - y_pred ** 2)

is evaluated as y_true - (y_pred ** 2) because exponentiation ** has higher precedence than subtraction.

For MSE, we must first calculate the difference between actual and predicted values and then square it:

mse = np.mean((y_true - y_pred) ** 2)

In [11]:

X = np.array([[1, 2],
              [2, 3],
              [3, 4]]) 
w = np.array([0.5, 1.0]) 
b = 2.0
y_pred = X @ w + b
y_true = np.array([10, 20, 30])
mse = np.mean((y_true - y_pred)** 2)
print("Predicted values:", y_pred)
print("MSE:", mse)

Predicted values: [4.5 6.  7.5]
MSE: 244.16666666666666


In [ ]:
#Implement min-max normalization for a 2D feature matrix on a per-column (per-feature) basis, rather than using a single global min/max for the whole array. Your solution must be fully vectorized, with no explicit loops over rows or columns

X=np.array([[10, 100], [20, 200], [30, 300]]) 
min_values=X.min(axis=0) 
max_values=X.max(axis=0) 
X_normalized = (X - min_values) / (max_values - min_values) 
print("Original matrix:") 
print(X) 
print("Normalized matrix:") 
print(X_normalized)

In [12]:
#Given a 1D array of exam scores, use a single vectorized expression (no if/else statements and no explicit loops) to classify each score as:
#Fail (< 40), Average (40–70 inclusive), or Excellent (> 70).
#Hint: You may need to nest or combine np.where() calls.
scores=np.array([20,50,80,97,40,50,30,35])
filter=np.where(scores<40, "Fail",
                np.where(scores<=70, "Average", "Excellent"))
print(filter)


['Fail' 'Average' 'Excellent' 'Excellent' 'Average' 'Average' 'Fail'
 'Fail']
