In [ ]:
#1.Create a NumPy array containing numbers from 10 to 100 with a step of 10.
import numpy as np
numpy_array=np.arange(10,101,10)
print(numpy_array)

[ 10  20  30  40  50  60  70  80  90 100]


In [5]:
#2. Create a 3 x 4 array of zeros.
zeros=np.zeros((3,4))
print(zeros)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
#3.Create an array and print its ndim, shape, size, and dtype.
array=np.array([[1,2,3],
                [4,5,6]])
print(array.ndim)
print(array.shape)
print(array.size)
print(array.dtype)

2
(2, 3)
6
int64


In [7]:
#4.Extract the last element from a 1D array.
array=np.array([10,20,30,40,50])
print(array[-1])

50


In [8]:
#5.Select the first two columns of a 2D array.
array=np.array([[1,2,3],
                [4,5,6]])
print(array[:,:2])

[[1 2]
 [4 5]]


In [9]:
#6.Reshape 12 numbers into a 3 x 4 matrix.
array=np.arange(1,13).reshape(3,4)
print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
#7.Transpose a 2 x 3 matrix.
array=np.arange(1,7).reshape(2,3)
print(array.T)

[[1 4]
 [2 5]
 [3 6]]


In [11]:
#8.Multiply every element of an array by 5.
array=np.array([10,20,30,40,50])
multiply=array*5
print(multiply)

[ 50 100 150 200 250]


In [12]:
#9.Create a feature matrix X with 5 samples and 3 features. Print its shape.
array=np.arange(1,16).reshape(5,3)
print(array.shape)

(5, 3)


In [13]:
#10.Calculate the mean of each feature using axis=0.
array=np.arange(1,7).reshape(2,3)
print("average (axis=0):",np.mean(array, axis=0))

average (axis=0): [2.5 3.5 4.5]


In [14]:
#11.Filter all rows where the first feature is greater than 50.
array=np.array([[25, 40, 44],
                [56, 43, 55],
                [88, 43, 68],
                [51, 23, 45]])
print(array[array[:,0]>50])

[[56 43 55]
 [88 43 68]
 [51 23 45]]


In [16]:
#12.Standardize every feature column
array=np.array([[20, 31,40],
               [32, 43, 54],
               [32, 42, 52]])
mean=np.mean(array, axis=0)
std=np.std(array, axis=0)
standardize=(array-mean)/std
print(standardize)



[[-1.41421356 -1.41022048 -1.40182605]
 [ 0.70710678  0.79708114  0.86266219]
 [ 0.70710678  0.61313934  0.53916387]]


In [5]:
#13.Create a random matrix of shape (10, 4) using a fixed seed.
import numpy as np
rng=np.random.default_rng(42)
matrix=rng.random((10,4))
print(matrix)

[[0.77395605 0.43887844 0.85859792 0.69736803]
 [0.09417735 0.97562235 0.7611397  0.78606431]
 [0.12811363 0.45038594 0.37079802 0.92676499]
 [0.64386512 0.82276161 0.4434142  0.22723872]
 [0.55458479 0.06381726 0.82763117 0.6316644 ]
 [0.75808774 0.35452597 0.97069802 0.89312112]
 [0.7783835  0.19463871 0.466721   0.04380377]
 [0.15428949 0.68304895 0.74476216 0.96750973]
 [0.32582536 0.37045971 0.46955581 0.18947136]
 [0.12992151 0.47570493 0.22690935 0.66981399]]


In [6]:
#14.14. Calculate X @ weights for a feature matrix and weight vector.
x=np.array([[1, 2, 3],
           [4, 5, 6]])
weights=np.array([7, 8, 9])
print("matrix multiplication:", x@weights)


matrix multiplication: [ 50 122]


In [7]:
#15.Add a bias vector using broadcasting
x=np.array([[1, 2, 3],
           [4, 5, 6]])
weights=np.array([7, 8, 9])
bias=np.array([10,11])
result=x@weights
broadcasting=result+bias
print("result:",result)
print("broadcasting:",broadcasting)


result: [ 50 122]
broadcasting: [ 60 133]


In [8]:
#16.Calculate MSE between y_true and y_pred.
y_true=np.array([30,40,50])
y_pred=np.array([35,45,52])
result=y_true-y_pred
square=np.square(result)
avg=np.mean(square)
print(avg)

18.0


In [9]:
#17.Create a 28 x 28 grayscale image and print its shape.
image=np.random.randint(0, 256, size=(28, 28))
print(image.shape)


(28, 28)


In [10]:
#18.Create a batch of 64 RGB images of size 224 x 224.
images = np.random.randint(0, 256, size=(64, 224, 224, 3))
print(images.shape)

(64, 224, 224, 3)


In [11]:
#19.Create an array containing NaN and calculate its NaN-safe mean
array=np.array([10,20,30,np.nan,40,50])
print("nan safe mean:",np.nanmean(array))

nan safe mean: 30.0


In [ ]:
#20.Explain the difference between A * B and A @ B in your own words.
'*' It multiplies corresponding elements
'@' It performs matrix multiplication, where rows of A are multiplied with columns of B and the results are added